### ISSUE TITLE
Issue or new feature

### ISSUE THREAD

**Issue by mikey1963** [abcd567a/mm2#1]
Hi,
I wondered if there is a way to make the modesmixer2 data persistent across a reboot?
Thanks, Mike.

**Comment by abcd567a** [comment]
As far as I know the answer is no.
However you may ask your question in following thread of radarspotting.com forum where Sergsero (the author of ModeSMixer2) frequenly visits and answers questions.

[ModeSDeco2 and ModeSMixer2 - console programs for RTLSDR and transcoding](https://radarspotting.com/forum/index.php/topic,2978.msg13471.html#msg13471)

&nbsp;

**Comment by abcd567a** [comment]
This is solved in latest version of modesmixer2
