### ISSUE TITLE
Raspberry Zero W, Raspbian Lite - Bullseye

### ISSUE THREAD

**Issue by CzarofAK** [abcd567a/mm2#2]
Running the script was successful.
But when i checked with
```
sudo systemctl status mm2
```
the following message appears:
```
...
Main PID: 622 (code=exited, status=132)
```

Whats the issue? Bullseye or the Zero?

**Comment by abcd567a** [comment]
I have installed modesmixer2 by the script on following two installs, and modesmixer works ok on both. 
(1) Raspberry Pi OS Bullseye on RPi Model 4
(2) Armbian Bullseye on OrangePiPC
This shows that the issue is with Pi Zero W.

**Comment by CzarofAK** [comment]
Yes, confirmed.
Is there going to be Zero support? i would be very helpfull for mobile systems.

**Comment by abcd567a** [comment]
The modesmixer2 binary has been written by Sergsero. I have only wriiten the script to install this binary with systemd support. As the issue is due to binary, you may report it in this thread created by Sergsero:

 https://radarspotting.com/forum/index.php?topic=2978.0

&nbsp;

**Comment by abcd567a** [comment]
As I dont have Raspberrypi Zero W or Zero 2 W, I cannot test. It is a possibility that some file got corrupted during download or installation. Please uninstall it completely by following commands, and then run the installation script again
```
sudo systemctl stop mm2 
sudo systemctl disable mm2 
sudo rm /lib/systemd/system/mm2.service 
sudo rm -rf /usr/share/mm2 
sudo rm /usr/bin/modesmixer2 
sudo userdel mm2 
```

**Comment by CzarofAK** [comment]
Same result with different images (like Raspian Lite, Raspbian Full aswell as dietpi).
Gave up on the Zero, guess they start to drop support for this 32bit board anyway.
Chromium lack also support on the Zero at the minute.
