### ISSUE TITLE
-db  BaseStation

### ISSUE THREAD

**Issue by toxa1983poloskov** [abcd567a/mm2#3]
version  does not work with the database file   BaseStation
key   --db   after restarting it does not start

**Comment by abcd567a** [comment]
Cannot help as you have given too little information.

Please copy-paste here the output of following command:

`cat /usr/share/mm2/mm2.conf  `

**Comment by toxa1983poloskov** [comment]
--inConnectId 192.168.0.7:30005:ADSB
--inConnectId 192.168.0.7:30105:MLAT
--web 8889
--db /home/pi/Downloads/BaseStation.sqb

**Comment by abcd567a** [comment]
Issue following commands to:

(1) Give ownership of Basestation.sqb to user mm2 (which runs the modesmixer2), 

(2) Restart modesmixer2.

```
sudo chown -R mm2:mm2 /home/pi/Downloads/BaseStation.sqb        

sudo systemctl restart mm2  

```
