### ISSUE TITLE
Update maps to OpenStreetMaps

### ISSUE THREAD

**Issue by faridfarhan28** [abcd567a/mm2#4]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/90016155/188202112-ea944c10-d225-47a2-bee6-90eed56d5b29.png">
hi, i like your apps but looks more better if you wanna to update your maps library by OpenStreetMaps API because that is FREE

https://wiki.openstreetmap.org/wiki/API

wonderfull apps, thanks for develope this feature :)

**Comment by abcd567a** [comment]
(1) I am NOT the developer of modesmixer2 application. Sergesero is the developer. My contribution is to write the installation script which downloads the Sergesero's modesmixer2 app, and creates files to start it by systemd.

(2) As I am not the developer of the modesmixer2 software, I cannot make the changes you have suggested.
